data:
  n_clusters: 2
  nt: 100
  nx: 101
  param_bounds:
    w:
    - 376.99111843077515
    - 628.3185307179587
model:
  D_hsizes:
  - 260
  - 260
  E_hsizes:
  - 260
  - 260
  lat_space: 16
  n_control: 2
  n_layers: 4
  n_units: 100
  noise: 0.0075
seed: 9
sensors:
  dof_layout: interleaved
  n_A_basis: 13
  n_SVD_basis: 15
  n_sensors: 16
  num_sensors: 50
  sensor_mode: vector_nodes
training:
  Qs:
    AE: 150
    AENODE: 200
    KINEMATIC: 60
    LASTSTEP: 80
    LS: 120
    ONESTEP: 60
    SPATIALDIFF: 120
    TEMPORALDIFF: 80
  lMB: 10
  lr: 0.001
  lr_patience: 40
  nBPP: 400
  nMB: 4000
  n_epoch: 5000
  patience: 1000
  resample_every_epochs: 10
  warmup: 200
