data:
  cluster_bounds: null
  n_clusters: null
  nt: 200
  nx: 101
  param_bounds:
    s:
    - 0.5
    - 0.9
    tau:
    - 0.015915494309189534
    - 0.15915494309189535
model:
  D_hsizes:
  - 120
  - 120
  E_hsizes:
  - 120
  - 120
  lat_space: 8
  noise: 0.0075
  n_control: 3
  n_layers: 2
  n_units: 300
training:
  n_epoch: 1000
  patience: 200
  lr: 0.01
  lMB: 4
  nMB: 200
  nBPP: 400
  lr_patience: 50
  Qs:
    AE: 100
    AENODE: 120
    ONESTEP: 40
    LASTSTEP: 70
    LS: 100
    TEMPORALDIFF: 80
    SPATIALDIFF: 120
seed: 9
sensors:
  n_A_basis: 13
  n_SVD_basis: 15
  n_sensors: 18
training: null
